version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: mecano-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nuella2006#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mecano-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mecano-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8222:8222"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - mecano-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8060:8060"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mecano_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nuella2006#
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - mecano-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8050:8050"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mecano_users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nuella2006#
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - mecano-network

  abonnement-service:
    build: ./abonnement-service
    container_name: abonnement-service
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mecano_abonnements
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nuella2006#
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - mecano-network

networks:
  mecano-network:
    driver: bridge

volumes:
  postgres_data: